# Generated by Django 3.2.9 on 2021-12-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_alter_forum_last_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='date_replied',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
